CREATE TABLE Actor
(
  ActorID VARCHAR NOT NULL,
  Actor_Name VARCHAR NOT NULL,
  Profile_URL VARCHAR NOT NULL,
  PRIMARY KEY (ActorID)
);

CREATE TABLE Genre
(
  GenreID VARCHAR NOT NULL,
  Genre_Name VARCHAR NOT NULL,
  PRIMARY KEY (GenreID)
);

CREATE TABLE TVShow
(
  ShowID VARCHAR NOT NULL,
  Name VARCHAR NOT NULL,
  Original_Name VARCHAR NOT NULL,
  First_air_date VARCHAR NOT NULL,
  Last_air_date VARCHAR NOT NULL,
  Seasons VARCHAR NOT NULL,
  Episodes VARCHAR NOT NULL,
  Status VARCHAR NOT NULL,
  Overview VARCHAR NOT NULL,
  Popularity VARCHAR NOT NULL,
  TMDb_Rating VARCHAR NOT NULL,
  Vote_Count VARCHAR NOT NULL,
  Poster_URL VARCHAR NOT NULL,
  Backdrop_URL VARCHAR NOT NULL,
  PRIMARY KEY (ShowID)
);

CREATE TABLE Character
(
  CharacterID VARCHAR NOT NULL,
  Character_Name VARCHAR NOT NULL,
  ActorID VARCHAR NOT NULL,
  ShowID VARCHAR NOT NULL,
  PRIMARY KEY (CharacterID),
  FOREIGN KEY (ActorID) REFERENCES Actor(ActorID),
  FOREIGN KEY (ShowID) REFERENCES TVShow(ShowID)
);

CREATE TABLE Creator
(
  Creator_Name VARCHAR NOT NULL,
  CreatorID VARCHAR NOT NULL,
  PRIMARY KEY (CreatorID)
);

CREATE TABLE Network
(
  NetworkID VARCHAR NOT NULL,
  Network_Name VARCHAR NOT NULL,
  Logo_URL VARCHAR NOT NULL,
  Country INT NOT NULL,
  PRIMARY KEY (NetworkID)
);

CREATE TABLE Studio
(
  StudioID VARCHAR NOT NULL,
  Studio_Name VARCHAR NOT NULL,
  Logo_URL VARCHAR NOT NULL,
  Country VARCHAR NOT NULL,
  PRIMARY KEY (StudioID)
);

CREATE TABLE categorized_as
(
  GenreID VARCHAR NOT NULL,
  ShowID VARCHAR NOT NULL,
  PRIMARY KEY (GenreID, ShowID),
  FOREIGN KEY (GenreID) REFERENCES Genre(GenreID),
  FOREIGN KEY (ShowID) REFERENCES TVShow(ShowID)
);

CREATE TABLE created_by
(
  CreatorID VARCHAR NOT NULL,
  ShowID VARCHAR NOT NULL,
  PRIMARY KEY (CreatorID, ShowID),
  FOREIGN KEY (CreatorID) REFERENCES Creator(CreatorID),
  FOREIGN KEY (ShowID) REFERENCES TVShow(ShowID)
);

CREATE TABLE produced_by
(
  StudioID VARCHAR NOT NULL,
  ShowID VARCHAR NOT NULL,
  PRIMARY KEY (StudioID, ShowID),
  FOREIGN KEY (StudioID) REFERENCES Studio(StudioID),
  FOREIGN KEY (ShowID) REFERENCES TVShow(ShowID)
);

CREATE TABLE features
(
  ActorID VARCHAR NOT NULL,
  ShowID VARCHAR NOT NULL,
  PRIMARY KEY (ActorID, ShowID),
  FOREIGN KEY (ActorID) REFERENCES Actor(ActorID),
  FOREIGN KEY (ShowID) REFERENCES TVShow(ShowID)
);

CREATE TABLE broadcast_by
(
  ShowID VARCHAR NOT NULL,
  NetworkID VARCHAR NOT NULL,
  PRIMARY KEY (ShowID, NetworkID),
  FOREIGN KEY (ShowID) REFERENCES TVShow(ShowID),
  FOREIGN KEY (NetworkID) REFERENCES Network(NetworkID)
);
